input SiteCreateInput {
  orgId: ID!
  name: String!
  location: [SiteLocationInput!]!
}

input SiteUpdateInput {
  id: ID!
  name: String
  location: [SiteLocationInput]
}

input SiteLocationInput {
  lat: Float!
  lng: Float!
}
